namespace Vellon.Application.DTOs.Volunteer;

public record CreateVolunteerDto(
    string FullName,
    string IdNumber,
    DateTime BirthDate,
    string Phone,
    string Email,
    string? Address,
    string? CurrentOccupation,
    string? AvailableDays,
    string? AvailableSchedule,
    int? WeeklyHours,
    string? SpecialAvailability,
    string? Skills,
    string? OtherSkills,
    string? PreviousVolunteerExperience,
    string? EducationLevel,
    string? Languages,
    string? InterestAreas,
    string? OtherInterestArea,
    string? Reference1Name,
    string? Reference1Relation,
    string? Reference1Phone,
    string? Reference1Email,
    string? Reference2Name,
    string? Reference2Relation,
    string? Reference2Phone,
    string? Reference2Email,
    string? Motivation,
    string? ExpectedContribution
);
