// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vellon.Infrastructure.Data;

#nullable disable

namespace Vellon.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vellon.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fundacionovejitas@gmail.com",
                            FullName = "Administrador General",
                            IsActive = true,
                            IsSuperAdmin = true,
                            PasswordHash = "$2a$11$KYNqFn.oE3gSp1qBQL38U.V3X24Ud5vIOlF66bEvPjLoJDcu9EEPO",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Vellon.Domain.Entities.ContactRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ContactRecords");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("text");

                    b.Property<decimal?>("MonthlyIncome")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Occupation")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("SocioeconomicStudyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Workplace")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SocioeconomicStudyId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.HouseholdItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcquisitionType")
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasPendingPayments")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SocioeconomicStudyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SocioeconomicStudyId");

                    b.ToTable("HouseholdItems");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityFrequency")
                        .HasColumnType("text");

                    b.Property<string>("AdditionalResources")
                        .HasColumnType("text");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<int?>("EstimatedBeneficiaries")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EstimatedEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FundingSource")
                        .HasColumnType("text");

                    b.Property<string>("GeographicLocation")
                        .HasColumnType("text");

                    b.Property<bool>("HasFunding")
                        .HasColumnType("boolean");

                    b.Property<string>("MainObjective")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PriorityPopulation")
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResponsibleEmail")
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResponsiblePhone")
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleRole")
                        .HasColumnType("text");

                    b.Property<string>("SelectionCriteria")
                        .HasColumnType("text");

                    b.Property<string>("SpecificObjectives")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetPopulation")
                        .HasColumnType("text");

                    b.Property<string>("TeamMembers")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalBudget")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.ProjectActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsible")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectActivities");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.ProjectBudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("FundingSource")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectBudgetItems");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.SocioeconomicStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AlimonyAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("AlimonyDetails")
                        .HasColumnType("text");

                    b.Property<decimal?>("CableExpense")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreditCardBank")
                        .HasColumnType("text");

                    b.Property<decimal?>("CreditCardDebt")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("DebtExpense")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("EducationExpense")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("FoodExpense")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("HasCreditCard")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSavings")
                        .HasColumnType("boolean");

                    b.Property<int?>("HousingDebtStatus")
                        .HasColumnType("integer");

                    b.Property<string>("HousingOwnerIdNumber")
                        .HasColumnType("text");

                    b.Property<string>("HousingOwnerName")
                        .HasColumnType("text");

                    b.Property<int>("HousingType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ImasSubsidy")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ImasSubsidyProgram")
                        .HasColumnType("text");

                    b.Property<bool>("IsAlimonyVoluntary")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MedicineExpense")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("OtherExpenses")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("OtherExpensesDetails")
                        .HasColumnType("text");

                    b.Property<decimal?>("OtherIncome")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("OtherIncomeDetails")
                        .HasColumnType("text");

                    b.Property<decimal?>("OtherInstitutionAid")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("OtherInstitutionAidDetails")
                        .HasColumnType("text");

                    b.Property<decimal?>("RentExpense")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool?>("RentIsUpToDate")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("SavingsAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("SavingsBank")
                        .HasColumnType("text");

                    b.Property<decimal?>("ServicesExpense")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SocioeconomicStudies");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AvailableDays")
                        .HasColumnType("text");

                    b.Property<string>("AvailableSchedule")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentOccupation")
                        .HasColumnType("text");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExpectedContribution")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InterestAreas")
                        .HasColumnType("text");

                    b.Property<string>("Languages")
                        .HasColumnType("text");

                    b.Property<string>("Motivation")
                        .HasColumnType("text");

                    b.Property<string>("OtherInterestArea")
                        .HasColumnType("text");

                    b.Property<string>("OtherSkills")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PreviousVolunteerExperience")
                        .HasColumnType("text");

                    b.Property<string>("Reference1Email")
                        .HasColumnType("text");

                    b.Property<string>("Reference1Name")
                        .HasColumnType("text");

                    b.Property<string>("Reference1Phone")
                        .HasColumnType("text");

                    b.Property<string>("Reference1Relation")
                        .HasColumnType("text");

                    b.Property<string>("Reference2Email")
                        .HasColumnType("text");

                    b.Property<string>("Reference2Name")
                        .HasColumnType("text");

                    b.Property<string>("Reference2Phone")
                        .HasColumnType("text");

                    b.Property<string>("Reference2Relation")
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.Property<string>("SpecialAvailability")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WeeklyHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("Vellon.Domain.Entities.SocioeconomicStudy", "Study")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("SocioeconomicStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.HouseholdItem", b =>
                {
                    b.HasOne("Vellon.Domain.Entities.SocioeconomicStudy", "Study")
                        .WithMany("HouseholdItems")
                        .HasForeignKey("SocioeconomicStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Vellon.Domain.Entities.Admin", "Admin")
                        .WithMany("ResetTokens")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.ProjectActivity", b =>
                {
                    b.HasOne("Vellon.Domain.Entities.Project", "Project")
                        .WithMany("Activities")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.ProjectBudgetItem", b =>
                {
                    b.HasOne("Vellon.Domain.Entities.Project", "Project")
                        .WithMany("BudgetItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.Admin", b =>
                {
                    b.Navigation("ResetTokens");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.Project", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("BudgetItems");
                });

            modelBuilder.Entity("Vellon.Domain.Entities.SocioeconomicStudy", b =>
                {
                    b.Navigation("FamilyMembers");

                    b.Navigation("HouseholdItems");
                });
#pragma warning restore 612, 618
        }
    }
}
